version: '3'
services:
  server1:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  server2:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  server3:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - server1
          - server2
          - server3
      ports:
          - '8000:8000'
  client:
    build:
      context: ./client/
    command: npm start
    image: nginx:1.15-alpine
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
      - ./data/nginx:/etc/nginx/conf.d
    # depends_on:
    #   - server
    ports:
      - "80:3000"
      - "443:443"
      - "3000:3000"
  certbot:
    image: certbot/certbot
volumes:
  server: