version: '3'
services:
  server1:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  server2:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  server3:
      build: ./server
      tty: true
      volumes:
        - './server/src:/code-output-dir'
  client:
    build:
      context: ./client/
    command: npm start
    image: node:9.4.0
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:3000"
      - "3000:3000"

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - server1
          - server2
          - server3
      ports:
          - '8000:8000'
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "3000:80"
volumes:
  server: